export default interface ISalOutgoDetail {
  outgo_detail_id?: number,
  outgo_id?: number,
  seq?: number,
  factory_id?: number,
  prod_id?: number,
  lot_no?: string,
  qty?: number,
  price?: number,
  money_unit_id?: number,
  exchange?: number,
  total_price?: number,
  unit_qty?: number | null,
  carry_fg?: boolean,
  order_detail_id?: number | null,
  outgo_order_detail_id?: number | null,
  from_store_id?: number,
  from_location_id?: number | null,
  remark?: string | null,
  barcode?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string,
  tenant_uuid?: string
}