export default interface IPrdOrder {
  order_id?: number,
  factory_id?: number,
  reg_date?: Date,
  order_no?: string,
  proc_id?: number,
  workings_id?: number,
  equip_id?: number | null,
  mold_id?: number | null,
  prod_id?: number,
  plan_qty?: number | null,
  qty?: number,
  seq?: number | null,
  shift_id?: number,
  worker_group_id?: number | null,
  work_fg?: boolean,
  start_date?: Date,
  end_date?: Date,
  complete_fg?: boolean,
  complete_date?: Date | null,
  sal_order_detail_id?: number | null,
  remark?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string,
  tenant_uuid?: string
}