export default interface IPrdWork {
  work_id?: number,
  factory_id?: number,
  reg_date?: string,
  order_id?: number,
  seq?: number,
  workings_id?: number,
  prod_id?: number,
  lot_no?: string,
  qty?: number,
  reject_qty?: number,
  shift_id?: number,
  complete_fg?: boolean,
  to_store_id?: number,
  to_location_id?: number | null,
  remark?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string,
}