get:
  description: |
    하나의 품목별 금형정보 데이터를 조회합니다.
  summary: 품목별 금형정보 데이터 단일 조회
  tags:
    - 품목별 금형정보(ProdMold)
  parameters:
    - name: uuid
      in: path
      description: 품목별 금형정보의 UUID 를 입력합니다.
      required: true
      schema:
        type: string
        format: uuid

  responses:
    200:
      description: Read OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../../schemas/common/default-response.schema.yaml
              - type: object
                properties:
                  datas:
                    description: Enable
                    type: object
                    properties:
                      value:
                        description: Enable
                        type: object
                        properties:
                          count:
                            description: 영향받은 데이터의 개수
                            type: number
                            format: int32
                            minimum: 0
                      raws:
                        description: 품목별 금형정보 데이터 목록
                        type: array
                        items:
                          allOf:
                            - $ref: ../../schemas/mld/prod-mold.schema.yaml#/prod_mold_uuid
                            - $ref: ../../schemas/mld/prod-mold.schema.yaml#/factory_uuid
                            - $ref: ../../schemas/std/factory.schema.yaml#/factory_cd
                            - $ref: ../../schemas/std/factory.schema.yaml#/factory_nm
                            - $ref: ../../schemas/mld/prod-mold.schema.yaml#/prod_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_cd
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_cd
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
                            - $ref: ../../schemas/std/model.schema.yaml#/model_cd
                            - $ref: ../../schemas/std/model.schema.yaml#/model_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/rev
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
                            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_cd
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_nm
                            - $ref: ../../schemas/mld/prod-mold.schema.yaml#/mold_uuid
                            - $ref: ../../schemas/mld/mold.schema.yaml#/mold_cd
                            - $ref: ../../schemas/mld/mold.schema.yaml#/mold_nm
                            - $ref: ../../schemas/mld/mold.schema.yaml#/mold_no
                            - $ref: ../../schemas/common/timestamp.schema.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml
