version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:557471975685:task-definition/td-production-iso"
        LoadBalancerInfo:
            ContainerName: "container-production-iso"
            ContainerPort: 3004