version: 0.0
os: linux
files:
  - source: /
    destination: /var/iso-server
hooks:
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application-start.sh
      timeout: 300
      runas: root