version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:557471975685:task-definition/iso-server"
        LoadBalancerInfo:
            ContainerName: "iso-server"
            ContainerPort: 4000