version: 0.0
os: linux
files:
  - source: /
    destination: /var/iso-server
hooks:
  ApplicationStop: 
    - location: ./shells/application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: ./shells/before-install.sh
      timeout: 300
      runas: root    
  AfterInstall:
    - location: ./shells/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./shells/application-start.sh
      timeout: 300
      runas: root