version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      # - yarn run lint
  build:
    commands:
      # - yarn test
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'