version: 0.2

phases:
  install:
    commands:
      # - sudo npm install
  pre_build:
    commands:
      # - yarn run lint
  build:
    commands:
      # - yarn test
  post_build:
    commands:
      # - sudo rm -rf node_modules
artifacts:
  files:
    - '**/*'