get:
  description: |
    하나의 품목 데이터를 조회합니다.
  summary: 품목 데이터 단일 조회
  tags:
    - 품목(Prod)
  parameters:
    - name: uuid
      in: path
      description: 품목의 UUID 를 입력합니다.
      required: true
      schema:
        $ref: ../../schemas/std/prod.schema.yaml#/uuid

  responses:
    200:
      description: Read OK
      content:
        application/json:
          schema: 
            allOf:
              - $ref: ../../schemas/common/default-response.schema.yaml
              - type: object
                properties:
                  datas:
                    description: Enable
                    type: object
                    properties:
                      value:
                        description: Enable
                        type: object
                        properties:
                          count: 
                            description: 영향받은 데이터의 개수
                            type: number
                            format: int32
                            minimum: 0
                      raws:
                        description: 품목 데이터 목록
                        type: array
                        items:
                          allOf:
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_cd
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_cd
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
                            - $ref: ../../schemas/std/model.schema.yaml#/model_cd
                            - $ref: ../../schemas/std/model.schema.yaml#/model_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/rev
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
                            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_cd
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/lot_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/use_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/active_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/bom_type_uuid
                            - $ref: ../../schemas/adm/bom-type.schema.yaml#/bom_type_cd
                            - $ref: ../../schemas/adm/bom-type.schema.yaml#/bom_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/width
                            - $ref: ../../schemas/std/prod.schema.yaml#/length
                            - $ref: ../../schemas/std/prod.schema.yaml#/height
                            - $ref: ../../schemas/std/prod.schema.yaml#/material
                            - $ref: ../../schemas/std/prod.schema.yaml#/color
                            - $ref: ../../schemas/std/prod.schema.yaml#/weight
                            - $ref: ../../schemas/std/prod.schema.yaml#/thickness
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_cd
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_min_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_supply_days
                            - $ref: ../../schemas/std/prod.schema.yaml#/sal_order_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_use_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_unit_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_safe_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_cd
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_cd
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_receive_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_proc_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_final_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_active_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_plan_type_uuid
                            - $ref: ../../schemas/adm/prd-plan-type.schema.yaml#/prd_plan_type_cd
                            - $ref: ../../schemas/adm/prd-plan-type.schema.yaml#/prd_plan_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_min
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_max
                            - $ref: ../../schemas/common/timestamp.schema.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml