get:
  description: |
    품목 데이터 목록을 조회합니다.
  summary: 품목 데이터 조회
  tags:
    - 품목(Prod)
  parameters:
    - name: use_fg
      in: query
      description: |
        품목의 사용여부에 따라 품목을 조회합니다.<br/>
        [전체 조회시 입력하지 않습니다.] <br/> 
        [true] 사용 품목 조회 <br/>
        [false] 미사용 품목 조회
      schema:
        type: boolean
        format: boolean
        
    - name: qms_receive_insp_fg
      in: query
      description: |
        품목의 수입검사여부에 따라 품목을 조회합니다.<br/>
        [전체 조회시 입력하지 않습니다.] <br/> 
        [true] 수입검사 대상 품목 조회 <br/>
        [false] 수입검사 미대상 품목 조회
      schema:
        type: boolean
        format: boolean

    - name: qms_proc_insp_fg
      in: query
      description: |
        품목의 공정검사여부에 따라 품목을 조회합니다.<br/>
        [전체 조회시 입력하지 않습니다.] <br/> 
        [true] 공정검사 대상 품목 조회 <br/>
        [false] 공정검사 미대상 품목 조회
      schema:
        type: boolean
        format: boolean

    - name: qms_final_insp_fg
      in: query
      description: |
        품목의 최종검사여부에 따라 품목을 조회합니다.<br/>
        [전체 조회시 입력하지 않습니다.] <br/> 
        [true] 최종검사 대상 품목 조회 <br/>
        [false] 최종검사 미대상 품목 조회
      schema:
        type: boolean
        format: boolean

    - name: prd_active_fg
      in: query
      description: |
        품목의 생산품여부에 따라 품목을 조회합니다.<br/>
        [전체 조회시 입력하지 않습니다.] <br/> 
        [true] 생산품 조회 <br/>
        [false] 생산품을 제외한 품목 조회
      schema:
        type: boolean
        format: boolean

  responses:
    200:
      description: Read OK
      content:
        application/json:
          schema: 
            allOf:
              - $ref: ../../schemas/common/default-response.schema.yaml
              - type: object
                properties:
                  datas:
                    description: Enable
                    type: object
                    properties:
                      value:
                        description: Enable
                        type: object
                        properties:
                          count: 
                            description: 영향받은 데이터의 개수
                            type: number
                            format: int32
                            minimum: 0
                      raws:
                        description: 품목 데이터 목록
                        type: array
                        items:
                          allOf:
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_cd
                            - $ref: ../../schemas/std/item-type.schema.yaml#/item_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_cd
                            - $ref: ../../schemas/std/prod-type.schema.yaml#/prod_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
                            - $ref: ../../schemas/std/model.schema.yaml#/model_cd
                            - $ref: ../../schemas/std/model.schema.yaml#/model_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/rev
                            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
                            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_cd
                            - $ref: ../../schemas/std/unit.schema.yaml#/unit_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/lot_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/use_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/active_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/bom_type_cd
                            - $ref: ../../schemas/adm/bom-type.schema.yaml#/bom_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/width
                            - $ref: ../../schemas/std/prod.schema.yaml#/length
                            - $ref: ../../schemas/std/prod.schema.yaml#/height
                            - $ref: ../../schemas/std/prod.schema.yaml#/material
                            - $ref: ../../schemas/std/prod.schema.yaml#/color
                            - $ref: ../../schemas/std/prod.schema.yaml#/weight
                            - $ref: ../../schemas/std/prod.schema.yaml#/thickness
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_uuid
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_cd
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_min_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/mat_supply_days
                            - $ref: ../../schemas/std/prod.schema.yaml#/sal_order_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_use_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_unit_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_safe_qty
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_uuid
                            - $ref: ../../schemas/std/store.schema.yaml#/store_cd
                            - $ref: ../../schemas/std/store.schema.yaml#/store_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_uuid
                            - $ref: ../../schemas/std/location.schema.yaml#/location_cd
                            - $ref: ../../schemas/std/location.schema.yaml#/location_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_receive_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_proc_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/qms_final_insp_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_active_fg
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_plan_type_cd
                            - $ref: ../../schemas/adm/prd-plan-type.schema.yaml#/prd_plan_type_nm
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_min
                            - $ref: ../../schemas/std/prod.schema.yaml#/prd_max
                            - $ref: ../../schemas/common/timestamp.schema.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml

post:
  description: |
    품목 데이터를 생성합니다.
  summary: 품목 데이터 생성
  tags:
    - 품목(Prod)
  requestBody:
    content:
      application/json:
        schema:
          required:
            - prod_no
            - prod_nm
            - item_type_uuid
            - unit_uuid
            - lot_fg
            - use_fg
            - active_fg
            - mat_order_fg
            - sal_order_fg
            - inv_use_fg
            - qms_receive_insp_fg
            - qms_proc_insp_fg
            - qms_final_insp_fg
            - prd_active_fg
          allOf:
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/rev
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
            - $ref: ../../schemas/std/prod.schema.yaml#/lot_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/bom_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/width
            - $ref: ../../schemas/std/prod.schema.yaml#/length
            - $ref: ../../schemas/std/prod.schema.yaml#/height
            - $ref: ../../schemas/std/prod.schema.yaml#/material
            - $ref: ../../schemas/std/prod.schema.yaml#/color
            - $ref: ../../schemas/std/prod.schema.yaml#/weight
            - $ref: ../../schemas/std/prod.schema.yaml#/thickness
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_min_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_supply_days
            - $ref: ../../schemas/std/prod.schema.yaml#/sal_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_unit_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_safe_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_receive_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_proc_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_final_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_plan_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_min
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_max
  responses:
    201:
      $ref: ../../responses/common/succeed-create.response.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml

put:
  description: |
    품목 데이터를 행(Row) 단위로 수정합니다.
  summary: 품목 데이터 수정
  tags:
    - 품목(Prod)
  requestBody:
    content:
      application/json:
        schema:
          required:
            - uuid
            - prod_no
            - prod_nm
            - item_type_uuid
            - unit_uuid
            - lot_fg
            - use_fg
            - active_fg
            - mat_order_fg
            - sal_order_fg
            - inv_use_fg
            - qms_receive_insp_fg
            - qms_proc_insp_fg
            - qms_final_insp_fg
            - prd_active_fg
          allOf:
            - $ref: ../../schemas/std/prod.schema.yaml#/uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/rev
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
            - $ref: ../../schemas/std/prod.schema.yaml#/lot_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/bom_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/width
            - $ref: ../../schemas/std/prod.schema.yaml#/length
            - $ref: ../../schemas/std/prod.schema.yaml#/height
            - $ref: ../../schemas/std/prod.schema.yaml#/material
            - $ref: ../../schemas/std/prod.schema.yaml#/color
            - $ref: ../../schemas/std/prod.schema.yaml#/weight
            - $ref: ../../schemas/std/prod.schema.yaml#/thickness
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_min_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_supply_days
            - $ref: ../../schemas/std/prod.schema.yaml#/sal_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_unit_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_safe_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_receive_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_proc_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_final_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_plan_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_min
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_max
  responses:
    201:
      $ref: ../../responses/common/succeed-update.response.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml

patch:
  description: |
    품목 데이터를 개별 항목 단위로 수정합니다.
  summary: 품목 데이터 수정
  tags:
    - 품목(Prod)
  requestBody:
    content:
      application/json:
        schema:
          required:
            - uuid
          allOf:
            - $ref: ../../schemas/std/prod.schema.yaml#/uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_no
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_nm
            - $ref: ../../schemas/std/prod.schema.yaml#/item_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_type_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/model_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/rev
            - $ref: ../../schemas/std/prod.schema.yaml#/prod_std
            - $ref: ../../schemas/std/prod.schema.yaml#/lot_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/bom_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/width
            - $ref: ../../schemas/std/prod.schema.yaml#/length
            - $ref: ../../schemas/std/prod.schema.yaml#/height
            - $ref: ../../schemas/std/prod.schema.yaml#/material
            - $ref: ../../schemas/std/prod.schema.yaml#/color
            - $ref: ../../schemas/std/prod.schema.yaml#/weight
            - $ref: ../../schemas/std/prod.schema.yaml#/thickness
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_unit_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_order_min_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/mat_supply_days
            - $ref: ../../schemas/std/prod.schema.yaml#/sal_order_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_use_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_unit_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_safe_qty
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_store_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/inv_to_location_uuid
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_receive_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_proc_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/qms_final_insp_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_active_fg
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_plan_type_cd
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_min
            - $ref: ../../schemas/std/prod.schema.yaml#/prd_max
  responses:
    201:
      $ref: ../../responses/common/succeed-update.response.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml

delete:
  description: |
    품목 데이터를 삭제합니다.
  summary: 품목 데이터 삭제
  tags:
    - 품목(Prod)
  requestBody:
    content:
      application/json:
        schema:
          required:
            - uuid
          allOf:
            - $ref: ../../schemas/std/prod.schema.yaml#/uuid
  responses:
    200:
      $ref: ../../responses/common/succeed-delete.response.yaml
    500:
      $ref: ../../responses/common/general-error.response.yaml