export default interface IMatReturnDetail {
  return_detail_id?: number,
  return_id?: number,
  seq?: number,
  factory_id?: number,
  prod_id?: number,
  unit_id?: number,
  convert_value?: number,
  lot_no?: string,
  qty?: number,
  price?: number,
  money_unit_id?: number,
  exchange?: number,
  total_price?: number,
  receive_detail_id: number | null,
  from_store_id: number,
  from_location_id: number | null,
  remark?: string | null,
  barcode?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string
}