import IStdEmp from '../../interfaces/std/emp.interface';
import BaseMigration from '../base-migration';
import config from '../../configs/config';

// Seed Datas
let seedDatas: IStdEmp[] = [
  {
    "emp_id": 1,
    "emp_cd": "001",
    "emp_nm": "이옥분",
    "uid": 1,
    "dept_id": 1,
    "grade_id": 6,
    "birthday": "1997-05-01",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "e5266b03-7b05-4c5b-91df-e6112f638c62"
  },
  {
    "emp_id": 2,
    "emp_cd": "002",
    "emp_nm": "한상규",
    "uid": undefined,
    "dept_id": 2,
    "grade_id": 6,
    "birthday": "1990-04-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "f04d1ce4-2048-408f-9560-83c0d15aa0df"
  },
  {
    "emp_id": 3,
    "emp_cd": "003",
    "emp_nm": "김애숙",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 7,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "19355268-40c8-4a9c-baac-52e77168a542"
  },
  {
    "emp_id": 9,
    "emp_cd": "009",
    "emp_nm": "황미옥",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "30b5569a-523c-4ec0-abdb-ad0f8c605fdb"
  },
  {
    "emp_id": 4,
    "emp_cd": "004",
    "emp_nm": "나지니",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "f6a4d9bc-d59d-44f0-8dc0-170df9ad6557"
  },
  {
    "emp_id": 5,
    "emp_cd": "005",
    "emp_nm": "암브리",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "0bd4c1aa-c214-47cc-83e8-420df00ec1bc"
  },
  {
    "emp_id": 6,
    "emp_cd": "006",
    "emp_nm": "윤광일",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "2bdb9484-fa40-407a-b634-220f4104e277"
  },
  {
    "emp_id": 7,
    "emp_cd": "007",
    "emp_nm": "허순애",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "b83d400a-13e6-446e-856d-9872b9e2c43a"
  },
  {
    "emp_id": 8,
    "emp_cd": "008",
    "emp_nm": "최문화",
    "uid": undefined,
    "dept_id": 4,
    "grade_id": 15,
    "birthday": "1990-05-05",
    "hp": undefined,
    "post": undefined,
    "addr": undefined,
    "addr_detail": undefined,
    "enter_date": "2021-02-02",
    "leave_date": undefined,
    "remark": undefined,
    "created_uid": 1,
    "updated_uid": 1,
    "uuid": "f3495e94-6e25-4d3c-91d8-ac2dc9cf1d4d"
  }
]

const baseMigration = new BaseMigration('StdEmp', 'emp_id', config.db.reset_type === 'test' ? seedDatas : []);
const migration = baseMigration.migration;
const migrationUndo = baseMigration.migrationUndo;

module.exports = { migration, migrationUndo };