import IStdDataMap from '../../interfaces/gat/data-map.interface';
import BaseMigration from '../base-migration';
import config from '../../configs/config';

// Seed Datas
let seedDatas: IStdDataMap[] = [
	{
		data_map_id : 5,
		data_map_nm : "가열로 1",
		data_gear_id : 1,
		data_item_id : 1,
		equip_id : 11,
		data_channel : "30017",
		history_yn : true,
		weight : 1,
		work_fg : false,
		community_function : "03.Read Holding Registers",
		slave : "1",
		alarm_fg : false,
		ieee752_fg : true,
		monitoring_fg : true,
		created_uid : 1,
		updated_uid : 1,
		uuid : "f73db261-c51e-450f-9b43-e585e9d91d77",
	},
	{
		data_map_id : 6,
		data_map_nm : "가열로 2",
		data_gear_id : 1,
		data_item_id : 1,
		equip_id : 11,
		data_channel : "30019",
		history_yn : true,
		weight : 1,
		work_fg : false,
		community_function : "03.Read Holding Registers",
		slave : "1",
		alarm_fg : false,
		ieee752_fg : true,
		monitoring_fg : true,
		created_uid : 1,
		updated_uid : 1,
		uuid : "594bbe81-3687-4ad9-b34b-9b5ab8a47c8f",
	},
	{
		data_map_id : 7,
		data_map_nm : "수조온도",
		data_gear_id : 1,
		data_item_id : 1,
		equip_id : 11,
		data_channel : "30021",
		history_yn : true,
		created_uid : 1,
		updated_uid : 1,
		uuid : "3c75e8d8-eeda-4fc8-bb31-e70caff95f27",
		slave : "1",
		alarm_fg : false,
		ieee752_fg : true,
		monitoring_fg : true,
		weight : 1,
		work_fg : false,
		community_function : "03.Read Holding Registers",
	},
	{
		data_map_id : 8,
		data_map_nm : "온도 4",
		data_gear_id : 1,
		data_item_id : 1,
		equip_id : 11,
		data_channel : "30023",
		history_yn : true,
		weight : 1,
		work_fg : false,
		community_function : "03.Read Holding Registers",
		slave : "1",
		alarm_fg : false,
		ieee752_fg : true,
		monitoring_fg : true,
		created_uid : 1,
		updated_uid : 1,
		uuid : "42029d8d-c371-460e-b297-7d9429dd3b86",
	},
	{
		data_map_id : 16,
		data_map_nm : null,
		data_gear_id : 13,
		data_item_id : 2,
		equip_id : 16,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "f749fa2b-09e8-4e0a-8d41-da8c2d406ca5",
	},
	{
		data_map_id : 17,
		data_map_nm : null,
		data_gear_id : 16,
		data_item_id : 2,
		equip_id : 17,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "41a33e22-6210-47a1-9151-8e534c47b0b3",
	},
	{
		data_map_id : 18,
		data_gear_id : 5,
		data_map_nm : null,
		data_item_id : 2,
		equip_id : 18,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "709a674a-b441-4ba2-a69d-1c77bea65c07",
	},
	{
		data_map_id : 19,
		data_map_nm : null,
		data_gear_id : 15,
		data_item_id : 2,
		equip_id : 19,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "9fb1024d-6475-471b-bea9-32be80f45b3f",
	},
	{
		data_map_id : 20,
		data_map_nm : null,
		data_gear_id : 11,
		data_item_id : 2,
		equip_id : 21,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "08ad556d-893d-4667-804b-1c91fdc8073c",
	},
	{
		data_map_id : 21,
		data_map_nm : null,
		data_gear_id : 6,
		data_item_id : 2,
		equip_id : 23,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "7774c39a-de45-4461-a98c-3f9155fb902b",
	},
	{
		data_map_id : 22,
		data_map_nm : null,
		data_gear_id : 7,
		data_item_id : 2,
		equip_id : 24,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "1371d6bc-3d52-4124-b68f-efd7e3b39adf",
	},
	{
		data_map_id : 23,
		data_map_nm : null,
		data_gear_id : 12,
		data_item_id : 2,
		equip_id : 25,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "472216d2-c9f6-4877-afb4-79cbd5b51715"
	},
	{
		data_map_id : 24,
		data_map_nm : null,
		data_gear_id : 10,
		data_item_id : 2,
		equip_id : 26,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "23ac68f0-c5fb-40fb-8421-bbe4007d6b87"
	},
	{
		data_map_id : 25,
		data_map_nm : null,
		data_gear_id : 14,
		data_item_id : 2,
		equip_id : 27,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "49ccb178-7b26-404c-9119-bedcd120ec97"
	},
	{
		data_map_id : 26,
		data_map_nm : null,
		data_gear_id : 8,
		data_item_id : 2,
		equip_id : 28,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : null,
		created_uid : 1,
		updated_uid : 1,
		uuid : "321a6835-47a0-4ef1-92a2-5417ec00175e"
	},
	{
		data_map_id : 27,
		data_map_nm : null,
		data_gear_id : 9,
		data_item_id : 2,
		equip_id : 40,
		data_channel : "2",
		history_yn : false,
		weight : 1,
		work_fg : true,
		community_function : null,
		slave : null,
		alarm_fg : false,
		ieee752_fg : false,
		monitoring_fg : false,
		created_uid : 1,
		updated_uid : 1,
		uuid : "47b488b2-43b9-4e0f-a94c-1ae094568107"
	}
]


const baseMigration = new BaseMigration('StdDataMap', 'data_map_id', config.db.reset_type === 'test' ? seedDatas : []);
const migration = baseMigration.migration;
const migrationUndo = baseMigration.migrationUndo;

module.exports = { migration, migrationUndo };