export default interface IEqmInspDetail {
  insp_detail_id?: number,
  insp_id?: number,
  seq?: number,
  factory_id?: number,
  insp_item_id?: number,
  insp_item_desc?: string | null,
  periodicity_fg?: boolean,
  spec_std?: string,
  spec_min?: string,
  spec_max?: string,
  insp_tool_id?: number | null,
  insp_method_id?: number | null,
  base_date?: string,
  daily_insp_cycle_id?: number | null,
  cycle_unit_id?: number | null,
  cycle?: number | null,
  sortby: number | null,
  remark?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string
}