# STD_PROD_TB

# Columns
prod_id: 
  type: object
  properties: 
    prod_id:
      description: 품목ID
      type: number
      format: int4
      
prod_no: 
  type: object
  properties: 
    prod_no:
      description: 품번
      type: string
      format: varchar(50)

prod_nm: 
  type: object
  properties: 
    prod_nm:
      description: 품목명
      type: string
      format: varchar(100)

item_type_id: 
  type: object
  properties: 
    item_type_id:
      description: 품목 유형ID
      type: number
      format: int4

prod_type_id: 
  type: object
  properties: 
    prod_type_id:
      description: 제품 유형ID
      type: number
      format: int4

model_id: 
  type: object
  properties: 
    model_id:
      description: 모델ID
      type: number
      format: int4

unit_id: 
  type: object
  properties: 
    unit_id:
      description: 단위ID
      type: number
      format: int4

rev: 
  type: object
  properties: 
    rev:
      description: 리비전
      type: string
      format: varchar(10)

prod_std: 
  type: object
  properties: 
    prod_std:
      description: 규격
      type: string
      format: varchar(250)

lot_fg: 
  type: object
  properties: 
    lot_fg:
      description: LOT 사용유무
      type: boolean
      format: boolean

use_fg: 
  type: object
  properties: 
    use_fg:
      description: 사용유무
      type: boolean
      format: boolean

active_fg: 
  type: object
  properties: 
    active_fg:
      description: 품목 활성 상태
      type: boolean
      format: boolean
      
bom_type_id: 
  type: object
  properties: 
    bom_type_id:
      description: BOM 유형ID
      type: number
      format: int4
      
width: 
  type: object
  properties: 
    width:
      description: 폭
      type: number
      format: numeric(19, 6)
      
length: 
  type: object
  properties: 
    length:
      description: 길이
      type: number
      format: numeric(19, 6)
      
height: 
  type: object
  properties: 
    height:
      description: 높이
      type: number
      format: numeric(19, 6)
      
material: 
  type: object
  properties: 
    material:
      description: 재질
      type: string
      format: varchar(20)

color: 
  type: object
  properties: 
    color:
      description: 색상
      type: string
      format: varchar(20)

weight: 
  type: object
  properties: 
    weight:
      description: 중량
      type: number
      format: numeric(19, 6)
      
thickness: 
  type: object
  properties: 
    thickness:
      description: 두께
      type: number
      format: numeric(19, 6)

mat_order_fg: 
  type: object
  properties: 
    mat_order_fg:
      description: 발주 사용유무
      type: boolean
      format: boolean

mat_unit_id: 
  type: object
  properties: 
    mat_unit_id:
      description: 구매단위ID
      type: number
      format: int4

mat_order_min_qty: 
  type: object
  properties: 
    mat_order_min_qty:
      description: 발주 최소 단위수량
      type: number
      format: numeric(19, 6)

mat_supply_days: 
  type: object
  properties: 
    mat_supply_days:
      description: 발주 소요일
      type: number
      format: numeric(19, 6)

sal_order_fg: 
  type: object
  properties: 
    sal_order_fg:
      description: 수주 사용유무
      type: boolean
      format: boolean

inv_use_fg: 
  type: object
  properties: 
    inv_use_fg:
      description: 창고 사용유무
      type: boolean
      format: boolean

inv_unit_qty: 
  type: object
  properties: 
    inv_unit_qty:
      description: 단위수량
      type: number
      format: numeric(19, 6)

inv_safe_qty: 
  type: object
  properties: 
    inv_safe_qty:
      description: 안전 재고수량
      type: number
      format: numeric(19, 6)

inv_to_store_id: 
  type: object
  properties: 
    inv_to_store_id:
      description: 입고 창고ID
      type: number
      format: int4

inv_to_location_id: 
  type: object
  properties: 
    inv_to_location_id:
      description: 입고 위치ID
      type: number
      format: int4

qms_receive_insp_fg: 
  type: object
  properties: 
    qms_receive_insp_fg:
      description: 수입검사유무
      type: boolean
      format: boolean

qms_proc_insp_fg: 
  type: object
  properties: 
    qms_proc_insp_fg:
      description: 공정검사유무
      type: boolean
      format: boolean

qms_final_insp_fg: 
  type: object
  properties: 
    qms_final_insp_fg:
      description: 최종검사유무
      type: boolean
      format: boolean

prd_plan_type_id: 
  type: object
  properties: 
    prd_plan_type_id:
      description: 계획유형ID (MPS/MRP)
      type: number
      format: int4

prd_active_fg: 
  type: object
  properties: 
    prd_active_fg:
      description: 생산품유무
      type: boolean
      format: boolean

prd_min: 
  type: object
  properties: 
    prd_min:
      description: 최소값
      type: number
      format: numeric(19, 6)

prd_max: 
  type: object
  properties: 
    prd_max:
      description: 최대값
      type: number
      format: numeric(19, 6)

uuid:
  type: object
  properties: 
    uuid:
      description: 품목UUID
      type: string
      format: uuid

# Uuids
prod_uuid:
  type: object
  properties: 
    prod_uuid:
      description: 품목UUID
      type: string
      format: uuid

item_type_uuid:
  type: object
  properties: 
    item_type_uuid:
      description: 품목 유형UUID
      type: string
      format: uuid

prod_type_uuid:
  type: object
  properties: 
    prod_type_uuid:
      description: 제품 유형UUID
      type: string
      format: uuid

model_uuid:
  type: object
  properties: 
    model_uuid:
      description: 모델UUID
      type: string
      format: uuid

unit_uuid:
  type: object
  properties: 
    unit_uuid:
      description: 단위UUID
      type: string
      format: uuid

bom_type_uuid:
  type: object
  properties: 
    bom_type_uuid:
      description: BOM 유형UUID
      type: string
      format: uuid

mat_unit_uuid:
  type: object
  properties: 
    mat_unit_uuid:
      description: 구매단위UUID
      type: string
      format: uuid

prd_plan_type_uuid: 
  type: object
  properties: 
    prd_plan_type_uuid:
      description: 계획유형UUID (MPS/MRP)
      type: string
      format: uuid

inv_to_store_uuid: 
  type: object
  properties: 
    inv_to_store_uuid:
      description: 입고 창고UUID
      type: string
      format: uuid

inv_to_location_uuid: 
  type: object
  properties: 
    inv_to_location_uuid:
      description: 입고 위치UUID
      type: string
      format: uuid

# Others
inv_to_store_cd: 
  type: object
  properties: 
    inv_to_store_cd:
      description: 입고 창고코드
      type: string
      format: varchar(20)

inv_to_store_nm: 
  type: object
  properties: 
    inv_to_store_nm:
      description: 입고 창고명
      type: string
      format: varchar(50)

inv_to_location_cd: 
  type: object
  properties: 
    inv_to_location_cd:
      description: 입고 위치코드
      type: string
      format: varchar(20)

inv_to_location_nm: 
  type: object
  properties: 
    inv_to_location_nm:
      description: 입고 위치명
      type: string
      format: varchar(50)

factory_cd: 
  type: object
  properties: 
    factory_cd:
      description: 공장코드
      type: string
      format: varchar(20)

unit_qty: 
  type: object
  properties: 
    unit_qty:
      description: 단위수량
      type: number
      format: numeric(19, 6)

mat_unit_cd: 
  type: object
  properties: 
    mat_unit_cd:
      description: 구매단위코드
      type: string
      format: varchar(20)

mat_unit_nm: 
  type: object
  properties: 
    mat_unit_nm:
      description: 구매단위명
      type: string
      format: varchar(50)