export default interface IStdPartner {
  partner_id?: number,
  partner_cd?: string,
  partner_nm?: string,
  partner_type_id?: number,
  partner_no?: string | null,
  boss_nm?: string | null,
  manager?: string | null,
  email?: string | null,
  tel?: string | null,
  fax?: string | null,
  post?: string | null,
  addr?: string | null,
  addr_detail?: string | null,
  use_fg?: boolean,
  vendor_fg?: boolean,
  customer_fg?: boolean,
  remark?: string | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string,
  tenant_uuid?: string
}