export default interface IStdProd {
  prod_id?: number,
  prod_no?: string,
  prod_nm?: string,
  item_type_id?: number,
  prod_type_id?: number | null,
  model_id?: number | null,
  rev?: string | null,
  prod_std?: string | null,
  unit_id?: number,
  lot_fg?: boolean,
  use_fg?: boolean,
  active_fg?: boolean,
  bom_type_cd?: string | null,
  material?: string | null,
  color?: string | null,
  width?: number | null,
  length?: number | null,
  height?: number | null,
  weight?: number | null,
  thickness?: number | null,
  mat_order_fg?: boolean,
  mat_unit_id?: number | null,
  mat_order_min_qty?: number | null,
  mat_supply_days?: number,
  sal_order_fg?: boolean,
  inv_use_fg?: boolean,
  inv_unit_qty?: number | null,
  inv_safe_qty?: number | null,
  inv_to_store_id?: number | null,
  inv_to_location_id?: number | null,
  qms_receive_insp_fg?: boolean,
  qms_proc_insp_fg?: boolean,
  qms_final_insp_fg?: boolean,
  prd_active_fg?: boolean,
  prd_plan_type_cd?: string | null,
  prd_min?: number | null,
  prd_max?: number | null,
  created_at?: Date,
  created_uid?: number,
  updated_at?: Date,
  updated_uid?: number,
  uuid?: string,
  tenant_uuid?: string
}