# MLD_PROD_MOLD_TB

# Columns
prod_mold_id:
  type: object
  properties:
    prod_mold_id:
      description: 품목별 금형정보ID
      type: number
      format: int4

factory_id:
  type: object
  properties:
    factory_id:
      description: 공장ID
      type: number
      format: int4

prod_id:
  type: object
  properties:
    prod_id:
      description: 품목ID
      type: number
      format: int4

mold_id:
  type: object
  properties:
    mold_id:
      description: 금형ID
      type: number
      format: int4

uuid:
  type: object
  properties:
    uuid:
      description: 품목별 금형정보UUID
      type: string
      format: uuid

# Uuids
prod_mold_uuid:
  type: object
  properties:
    prod_mold_uuid:
      description: 품목별 금형정보UUID
      type: string
      format: uuid

factory_uuid:
  type: object
  properties:
    factory_uuid:
      description: 공장UUID
      type: string
      format: uuid

prod_uuid:
  type: object
  properties:
    prod_uuid:
      description: 품목UUID
      type: string
      format: uuid

mold_uuid:
  type: object
  properties:
    mold_uuid:
      description: 금형UUID
      type: string
      format: uuid